version: '3'
services:
    db:
        container_name: db
        image: postgres:16
        volumes:
            - ./db/postgres:/var/lib/postgresql/data/
        ports:
            - 5433:5432
        env_file:
            - .env
        networks:
            - network

    redis:
        container_name: redis
        ports:
            - 6379:6379
        volumes:
            - ./db/redis:/data
        image: redis:7-alpine
        networks:
            - network

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:management
        env_file:
            - .env
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - network

    web:
        container_name: web
        restart: always
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - 8002:8000
        env_file:
            - .env
        volumes:
            - ./app:/app
        depends_on:
            - db
            - redis
        networks:
            - network

    celery:
        container_name: celery
        build:
            context: .
        command: celery -A main worker --loglevel=info
        volumes:
            - ./app:/app
        env_file:
            - .env
        depends_on:
            - web
            - redis
            - rabbitmq
        networks:
            - network

    celery-beat:
        container_name: celery-beat
        build:
            context: .
        command: celery -A main beat --loglevel=Error
        env_file:
            - .env
        volumes:
            - ./app:/app
        depends_on:
            - celery
        networks:
            - network
            
    # flower:
    #     container_name: flower
    #     build:
    #         context: .
    #     volumes:
    #         - ./app:/app
    #     ports:
    #         - "5555:5555"
    #     command: sh -c "sleep 2 && celery -A main flower"
    #     depends_on:
    #         - celery
    #         - celery-beat

networks:
  network: