# Generated by Django 4.2.5 on 2023-11-14 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdsInThree',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField(default=0.0)),
                ('name', models.CharField(max_length=100)),
                ('fiat', models.CharField(max_length=10)),
                ('token', models.CharField(max_length=10)),
                ('buy_sell', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=4)),
                ('order_q', models.IntegerField(default=0)),
                ('order_p', models.FloatField(default=0.0)),
                ('lim_min', models.FloatField(default=0.0)),
                ('lim_max', models.FloatField(default=0.0)),
                ('adv_no', models.CharField(max_length=50)),
                ('available', models.FloatField(default=0.0, max_length=30)),
                ('exchange', models.CharField(max_length=50)),
                ('best_payment', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Ads in three actions',
                'verbose_name_plural': 'Sell Ads',
            },
        ),
        migrations.CreateModel(
            name='AdsInTwo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField(default=0.0)),
                ('name', models.CharField(max_length=100)),
                ('fiat', models.CharField(max_length=10)),
                ('token', models.CharField(max_length=10)),
                ('buy_sell', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=4)),
                ('order_q', models.IntegerField(default=0)),
                ('order_p', models.FloatField(default=0.0)),
                ('lim_min', models.FloatField(default=0.0)),
                ('lim_max', models.FloatField(default=0.0)),
                ('adv_no', models.CharField(max_length=50)),
                ('available', models.FloatField(default=0.0, max_length=30)),
                ('exchange', models.CharField(max_length=50)),
                ('best_payment', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Ads in two actions',
                'verbose_name_plural': 'Buy Ads',
            },
        ),
        migrations.CreateModel(
            name='BestLinksInTwoActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spread', models.FloatField()),
                ('buy_ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buy_ad', to='count.adsintwo')),
                ('sell_ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sell_ad', to='count.adsintwo')),
            ],
        ),
        migrations.CreateModel(
            name='BestLinksInThreeActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spread', models.FloatField()),
                ('spot', models.FloatField()),
                ('buy_ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buy_ad', to='count.adsinthree')),
                ('sell_ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sell_ad', to='count.adsinthree')),
            ],
        ),
    ]
