# Generated by Django 4.2.5 on 2023-11-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kucoin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField(default=0.0)),
                ('name', models.CharField(max_length=100)),
                ('payments', models.JSONField()),
                ('fiat', models.CharField(max_length=10)),
                ('token', models.CharField(max_length=10)),
                ('buy_sell', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=4)),
                ('order_q', models.IntegerField(default=0)),
                ('order_p', models.FloatField(default=0.0)),
                ('lim_min', models.FloatField(default=0.0)),
                ('lim_max', models.FloatField(default=0.0)),
                ('adv_no', models.CharField(max_length=50)),
                ('available', models.FloatField(default=0.0, max_length=30)),
                ('available_rub', models.FloatField(default=0.0, max_length=30)),
                ('exchange', models.CharField(default='Kucoin')),
            ],
            options={
                'db_table': 'exchange_kucoin',
            },
        ),
        migrations.CreateModel(
            name='TotalCoin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField(default=0.0)),
                ('name', models.CharField(max_length=100)),
                ('payments', models.JSONField()),
                ('fiat', models.CharField(max_length=10)),
                ('token', models.CharField(max_length=10)),
                ('buy_sell', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=4)),
                ('order_q', models.IntegerField(default=0)),
                ('order_p', models.FloatField(default=0.0)),
                ('lim_min', models.FloatField(default=0.0)),
                ('lim_max', models.FloatField(default=0.0)),
                ('adv_no', models.CharField(max_length=50)),
                ('available', models.FloatField(default=0.0, max_length=30)),
                ('available_rub', models.FloatField(default=0.0, max_length=30)),
                ('exchange', models.CharField(default='TotalCoin')),
            ],
            options={
                'db_table': 'exchange_totalcoin',
            },
        ),
    ]
