# Generated by Django 4.2.5 on 2023-12-03 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0003_banksparsing_banksparsingtotalcoin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banksparsingtotalcoin',
            name='name',
        ),
        migrations.AlterModelTable(
            name='bybitmodel',
            table='Bybit',
        ),
        migrations.AlterModelTable(
            name='garantexmodel',
            table='Garantex',
        ),
        migrations.AlterModelTable(
            name='gateiomodel',
            table='Gate.io',
        ),
        migrations.AlterModelTable(
            name='hodlhodlmodel',
            table='Hodl Hodl',
        ),
        migrations.AlterModelTable(
            name='huobimodel',
            table='Huobi',
        ),
        migrations.AlterModelTable(
            name='kucoinmodel',
            table='Kucoin',
        ),
        migrations.AlterModelTable(
            name='totalcoinmodel',
            table='TotalCoin',
        ),
        migrations.DeleteModel(
            name='BanksParsing',
        ),
        migrations.DeleteModel(
            name='BanksParsingTotalCoin',
        ),
    ]
