# Generated by Django 4.2.5 on 2023-12-03 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0004_remove_banksparsingtotalcoin_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kucoinmodel',
            table='kucoin',
        ),
    ]
