# Generated by Django 4.2.5 on 2023-12-03 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0005_alter_kucoinmodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='totalcoinmodel',
            table='totalcoin',
        ),
    ]
